import packageJson from '../../package.json';
import { COLOR_BORDER_DARK, COLOR_BORDER_LIGHT } from '../const';
import { generateHiddenColumn, generateStringValue, generateTitleColumn } from './sheetUtils';

const generateTitleRows = (baseBranch, remote) => [
  {
    values: [
      generateHiddenColumn(packageJson.version),
      {
        span: { cols: 2, rows: 3 },
        col: generateTitleColumn('Git Housekeeper'),
      },
      {
        span: { cols: 3 },
        col: {
          ...generateStringValue(`sheet generated by ${packageJson.name}`),
        },
      },
      {
        userEnteredValue: {
          formulaValue: `=HYPERLINK("${packageJson.homepage}", "click here for more info")`,
        },
        userEnteredFormat: {
          horizontalAlignment: 'CENTER',
          borders: {
            right: {
              style: 'SOLID',
              color: COLOR_BORDER_DARK,
            },
          },
        },
      },
      {
        span: { cols: 2, rows: 3 },
        col: {
          ...generateStringValue(`base branch: ${baseBranch}`),
          userEnteredFormat: {
            horizontalAlignment: 'CENTER',
            verticalAlignment: 'BOTTOM',
            wrapStrategy: 'WRAP',
            borders: {
              right: {
                style: 'SOLID',
                color: COLOR_BORDER_LIGHT,
              },
            },
          },
        },
      },
    ],
  },
  {
    values: [
      generateHiddenColumn(remote.name),
      {},
      {},
      {
        span: { cols: 4 },
        col: {
          ...generateStringValue(
            'instructions: for each branch, select the desired action in the "action" column',
          ),
          userEnteredFormat: {
            borders: {
              right: {
                style: 'SOLID',
                color: COLOR_BORDER_DARK,
              },
            },
          },
        },
      },
    ],
  },
  {
    values: [
      generateHiddenColumn(remote.url),
      {},
      {},
      {
        span: { cols: 4 },
        col: {
          ...generateStringValue(
            'do not edit the first column (pink background). feel free to make other changes',
          ),
          userEnteredFormat: {
            borders: {
              bottom: {
                style: 'SOLID',
                color: COLOR_BORDER_DARK,
              },
              right: {
                style: 'SOLID',
                color: COLOR_BORDER_DARK,
              },
            },
          },
        },
      },
    ],
  },
];

export default generateTitleRows;
